// Generated by tools/gen_opla_table.py from
// development-assets/mm77la_mfootb2_output.pla -- do not hand-edit.
#pragma once
#include <cstdint>
#include <array>

static constexpr std::array<uint16_t, 16> kOplaTable = {
    0x2A8,
    0x3AF,
    0x2B2,
    0x2A3,
    0x3A5,
    0x2E1,
    0x2E0,
    0x2AF,
    0x2A0,
    0x2A1,
    0x3DF,
    0x37F,
    0x1FF,
    0x3A7,
    0x3F4,
    0x3FF,
};
