#!/usr/bin/env python3
# tools/gen_opla_table.py
#
# Parses development-assets/mm77la_mfootb2_output.pla (Berkeley PLA text
# format) into a 16-entry A -> raw-10-bit-output lookup table, then emits it
# as both a Verilog case statement and a C++ array.
#
# Row order in the .pla file is a Gray-code-like enumeration, NOT binary
# counting order (see docs/superpowers/specs/2026-08-02-io-peripherals-phase2-design.md
# section 2 for the full derivation against MAME's plaparse.cpp/pla.cpp) --
# each row is matched by its literal input pattern, not by file position.
# Within a row, the LEFTMOST input character is bit 0 (LSB) of A, and output
# columns map directly left-to-right to output bits 0..9 (no inversion).
import sys

def parse_pla(path):
    with open(path) as f:
        lines = [ln.strip() for ln in f if ln.strip() and not ln.startswith('.') and not ln.startswith('#')]
    table = {}
    for line in lines:
        inp, out = line.split()
        a = 0
        for j, c in enumerate(inp):
            if c == '1':
                a |= (1 << j)
        raw = 0
        for f, c in enumerate(out):
            if c == '1':
                raw |= (1 << f)
        if a in table:
            raise ValueError(f"duplicate input pattern for A={a:#x}")
        table[a] = raw
    if sorted(table.keys()) != list(range(16)):
        raise ValueError(f"expected all 16 input patterns, got {sorted(table.keys())}")
    return [table[a] for a in range(16)]

def emit_verilog(table, path):
    with open(path, 'w') as f:
        f.write("// Generated by tools/gen_opla_table.py from\n")
        f.write("// development-assets/mm77la_mfootb2_output.pla -- do not hand-edit.\n")
        f.write("function [9:0] opla_table(input [3:0] a);\n")
        f.write("    case (a)\n")
        for a, raw in enumerate(table):
            f.write(f"        4'h{a:X}: opla_table = 10'h{raw:03X};\n")
        f.write("        default: opla_table = 10'h000;\n")
        f.write("    endcase\n")
        f.write("endfunction\n")

def emit_cpp(table, path):
    with open(path, 'w') as f:
        f.write("// Generated by tools/gen_opla_table.py from\n")
        f.write("// development-assets/mm77la_mfootb2_output.pla -- do not hand-edit.\n")
        f.write("#pragma once\n#include <cstdint>\n#include <array>\n\n")
        f.write("static constexpr std::array<uint16_t, 16> kOplaTable = {\n")
        for raw in table:
            f.write(f"    0x{raw:03X},\n")
        f.write("};\n")

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <in.pla> <out.vh> <out.h>", file=sys.stderr)
        sys.exit(2)
    table = parse_pla(sys.argv[1])
    emit_verilog(table, sys.argv[2])
    emit_cpp(table, sys.argv[3])
    print(f"wrote {sys.argv[2]} and {sys.argv[3]}")
