// Field background bitmap: green background, endzones, 10 field columns
// with dividers and a single hash-tick row, stored as an indexed bitmap.
// Generated by tools/gen_bezel_bitmaps.py -- geometry/colors measured
// from a photo of the real FBII device (see that script's module
// docstring). This bitmap includes BORDER_W=4 pixels of margin above and
// below the 108px strip itself (see build_field_image()), so field_y
// spans 0-115 (108+2*4), not just 0-107.
module field_rom (
    input  wire [8:0]  x,        // 0-399
    input  wire [7:0]  field_y,  // 0-115
    output wire [23:0] rgb
);
    reg [7:0]  pixel_idx [0:46399];
    initial $readmemh("field_bitmap.mem", pixel_idx);

    reg [23:0] palette [0:255];
    initial $readmemh("field_palette.mem", palette);

    /* verilator lint_off WIDTHEXPAND */
    wire [15:0] addr = ({8'd0, field_y} * 16'd400) + {7'd0, x};
    /* verilator lint_on WIDTHEXPAND */
    assign rgb = palette[pixel_idx[addr]];
endmodule
