// Label text bitmap: the two label-bar strips ("DOWN"/"FIELD POSITION"/
// "YARDS TO GO" and "HOME"/"TIME REMAINING"/"VISITORS"), stored as a
// small indexed bitmap. Generated by tools/gen_bezel_bitmaps.py by
// rendering real font glyphs (not cropped from a source image -- FBII
// has no equivalent pre-made overlay asset, unlike FB1).
module label_rom (
    input  wire [8:0]  x,       // 0-399
    input  wire [4:0]  band_y,  // 0-31: 0-15 = bar1, 16-31 = bar2
    output wire [23:0] rgb
);
    reg [6:0]  pixel_idx [0:12799];
    initial $readmemh("label_bitmap.mem", pixel_idx);

    reg [23:0] palette [0:127];
    initial $readmemh("label_palette.mem", palette);

    /* verilator lint_off WIDTHEXPAND */
    wire [13:0] addr = ({9'd0, band_y} * 14'd400) + {5'd0, x};
    /* verilator lint_on WIDTHEXPAND */
    assign rgb = palette[pixel_idx[addr]];
endmodule
