// Generated by tools/gen_opla_table.py from
// development-assets/mm77la_mfootb2_output.pla -- do not hand-edit.
function [9:0] opla_table(input [3:0] a);
    case (a)
        4'h0: opla_table = 10'h2A8;
        4'h1: opla_table = 10'h3AF;
        4'h2: opla_table = 10'h2B2;
        4'h3: opla_table = 10'h2A3;
        4'h4: opla_table = 10'h3A5;
        4'h5: opla_table = 10'h2E1;
        4'h6: opla_table = 10'h2E0;
        4'h7: opla_table = 10'h2AF;
        4'h8: opla_table = 10'h2A0;
        4'h9: opla_table = 10'h2A1;
        4'hA: opla_table = 10'h3DF;
        4'hB: opla_table = 10'h37F;
        4'hC: opla_table = 10'h1FF;
        4'hD: opla_table = 10'h3A7;
        4'hE: opla_table = 10'h3F4;
        4'hF: opla_table = 10'h3FF;
        default: opla_table = 10'h000;
    endcase
endfunction
